version: '2.2'
services:

  app:
    build:
      context: .
    image: webscraping-elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - ES_URL=http://elasticsearch:9200
      - ARTICLE_URL=https://en.wikipedia.org/wiki/Special:Random
    volumes:
      - .:/app
    networks:
      - default


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=demo
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: es_demo

volumes:
  es_data:
